### ISSUE TITLE
/usr/local/bin/keymaker-create-account-for-iam-user  not installed

### ISSUE THREAD

**Issue by quagly** [kislyuk/keymaker#50]
Issue: missing /usr/local/bin/keymaker-create-account-for-iam-user  on keymaker install

Replication:

ran `sudo keymaker install` on fresh amazon-linux-2 instance.  Installation went fine but there was no /usr/local/bin/keymaker-create-account-for-iam-user  file created.  I looked at the install code and did not find this file deployed.  I copied the file from the repo and it worked fine.  

ssh -V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by quagly** [comment]
Resolved this for now by adding the following yaml to cfn-init

```
files:
              /usr/local/bin/keymaker-create-account-for-iam-user:
                source: https://raw.githubusercontent.com/kislyuk/keymaker/master/scripts/keymaker-create-account-for-iam-user
                mode: "000755"
                owner: "root"
                group: "root"
```
